import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import { getSessionCookie, getUserRoleFromSession } from "@/libs/cookie";

export const metadata: Metadata = {
  title: "SESSION Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionCookie = await getSessionCookie();
  const session = sessionCookie?.value ?? null;

  const role = session ? await getUserRoleFromSession() : null;

  return (
    <html lang="en">
      <body className="relative">
        <Navbar initialSession={session} initialRole={role} />
        <main>{children}</main>
      </body>
    </html>
  );
}
